language: csharp
dotnet: 2.2.101
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
mono:
 - latest
matrix:
  include:
    - os: linux
      dist: xenial      
      sudo: required
      install:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-2.2
    - os: osx
      osx_image: xcode9       
      sudo: required
      install:
        - ulimit -n8192  
        - sudo curl -L https://download.visualstudio.microsoft.com/download/pr/244e2914-a8f7-4663-b661-157a5acfba9a/557328144b62e5d0207572e5f2a61f82/dotnet-sdk-2.2.101-osx-x64.pkg -o dotnet-sdk.pkg
        - sudo installer -pkg dotnet-sdk.pkg -target /
        - dotnet --info        
script:      
  - chmod +x build.sh
  - ./build.sh
